from tkinter import *
win = Tk()
win.title("Practice")
win.geometry("500x500")
win.attributes("-topmost",True)
hello=Label(win,text="Hello world!", font=("Arial",19))
hello.pack()
textbox=Text(win,height=1,font=("Arial",16))
textbox.pack()
button= Button(win, text="CLICK ME", font=("Arial",16))
button.pack()
buttonframe =Frame(win)
buttonframe.columnconfigure(0,weight=1)
buttonframe.columnconfigure(1,weight=1)
buttonframe.columnconfigure(2,weight=1)
btn1 =Button(buttonframe,text="1")
btn1.grid(row=0,column=0,sticky=W+E)
btn2 =Button(buttonframe,text="2")
btn2.grid(row=0,column=1,sticky=W+E)
btn3 =Button(buttonframe,text="3")
btn3.grid(row=0,column=2,sticky=W+E)
buttonframe.pack(fill='x')
win.mainloop()